# Generated by Django 2.1.1 on 2018-12-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(max_length=20)),
                ('Room_no', models.IntegerField()),
                ('Cust_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('Email_id', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('phone_no', models.IntegerField()),
                ('message', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=20)),
                ('Room_type', models.CharField(max_length=20)),
                ('Check_in', models.DateField()),
                ('Check_out', models.DateField()),
                ('Contact_no', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('Total_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Card_no', models.IntegerField()),
                ('Card_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('rpassword', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
